var parent = require('../../es/array');
require('../../modules/es.map');
require('../../modules/esnext.array.at');
require('../../modules/esnext.array.filter-out');
require('../../modules/esnext.array.find-last');
require('../../modules/esnext.array.find-last-index');
require('../../modules/esnext.array.is-template-object');
require('../../modules/esnext.array.last-item');
require('../../modules/esnext.array.last-index');
require('../../modules/esnext.array.popped');
require('../../modules/esnext.array.pushed');
require('../../modules/esnext.array.reversed');
require('../../modules/esnext.array.shifted');
require('../../modules/esnext.array.sorted');
require('../../modules/esnext.array.spliced');
require('../../modules/esnext.array.unique-by');
require('../../modules/esnext.array.unshifted');
require('../../modules/esnext.array.with');

module.exports = parent;
